event_type = ['Information Against Police', 'Threat In Person', 'Dispute',
       'Gambling', 'Missing', 'Theft', 'Domestic Violence',
       'Property Disputes', 'Illegal Mining', 'Suicide', 'Corona',
       'Cyber Crimes', 'Female Sexual Harrassment',
       'Unclaimed Information', 'Encroachment',
       'Crime On Phone Mobile Social Media Internet', 'Animals Related',
       'Unknown', 'Robbery', 'Pollution',
       'Information Against Other Government Departments', 'Medium Fire',
       'Child Crime(Sexual Abuse)', 'Found Deadbody',
       'Suspicious Object Information',
       'Threat On Phone Email Social Media', 'Dacoity',
       'Attempted Murder', 'Suspicious Person Information', 'Forgery',
       'Female Harrassment', 'Kidnap', 'Excise Act Offenses', 'Accident',
       'Ndps Act Offenses', 'Police Help Required By 108',
       'Escort For Safety', 'Traffic Jam', 'Differently Abled People',
       'Sos', 'Murder', 'Assault/Riot/Commotion', 'Major Fire',
       'Child Crime', 'Dowry Related Crime', 'Small Fire', 'Pick Pocket',
       'Election Offences-Violation Of Model Code Of Conduct',
       'Animals Smugling', 'Accident Explosive', 'Personally Threat',
       'Human Trafficking', 'Police Help Required By 1090',
       'Suicide Attempt'] 

event_sub_type = ['Misbehavior By Prv', 'Attack', 'Dispute In Hospital',
       'Play Cards', 'Grp- Person Accident By Train ',
       'Misbehavior By Ps Incharge', 'Gold Shop',
       'Dispute With Drunk Person', 'Money Transactions Dispute',
       'Family Dispute With Sr. Citizen', 'Threatening To Kill',
       'House Capture',
       'No Action Has Been Taken By Ps Incharge For Delivery Of Person Vehicle Goods By ',
       'Boundary Dispute', 'Beat Children By Familymembers',
       'Other Dispute', 'Other Location', 'Two Wheeler Vehicle',
       'Illegal Mining Land', 'By Hanging', 'Residential Building',
       'Husband To Beat Wife', 'Suspect Found Infected',
       'Bank Account Hacking', 'Teasing On Public Place', 'Unclaimed Men',
       'Expellinghouse Wife By Husband Or Family Members From House',
       'Government Land', 'Abuse Men', 'Sewer Dispute',
       'Found Injured Animal', 'Unknown', 'Women',
       'Cow Carcass And Slaughtering', 'On Road', 'Help For Other',
       'With Neighbor', 'Dispute With Service Provider Or Vendor',
       'Prv Has Taken Money From The Caller', 'Illegal Mining',
       'Black Marketing Over Stocking', 'Dispute Between Ride And Driver',
       'Abuse Women', 'Pollution By Dj/Band/Cracker/Others Means',
       'Beating Senior Citizen', 'Notice Of Negligence In Work',
       'Betting', 'Open School/Coaching Institution/College/Office',
       'Demand For Money By Ps Station Incharge',
       'Dispute With Unknown Person', 'Help For Food Items',
       'Gathering On Street Park', 'Gathering Funeral Other Celebration',
       'Building Res Insti Auditorial Academic Professional Indus Storage Multiplex Etc',
       'Husband Relatives To Beat Wife',
       'Obtain Illegally Atm / Bank  Information',
       'Dispute Between Hijras', 'Threaten Women', 'Male Dead Body',
       'Gathering Vegetable Market',
       'Information About Suspicious Object In Building/Campus/Location',
       'House', 'Four Wheeler Vehicle', 'Beaten With Lathi/Stick',
       'Threaten Men',
       'Information About Suspicious Person In Building/Campus/Place',
       'Other Kind Torturing To Senior Citizen',
       'Attempted Rape In Building Or Campus', 'Forged Signature',
       'Gathering Crowd Market', 'Sound Pollution',
       'Pollution From Industry', 'Mobile', 'Insult', 'Child Kidnap',
       'Obscene Message / Picture Post Of Women', 'Iilegal Sale',
       'Domestic Violence Against Men Or Boy Or Seniormen',
       'Business Establishment', 'Public Gathering',
       'Landlord And Tenant', 'Serious Road Accident',
       'Illegally Transfer Money From Bank', 'Kidnapping', 'Men Kidnap',
       'Quarantine Violation', 'Other Animal Carcass',
       'Sale Of Meat In Open', 'For Parking', 'Women Kidnap',
       'Police Help Required By 108', 'Pan Card', 'Iilegal Construction',
       'Alone', 'Dangerous Animals/Dog Residential Area',
       'Family Members Beat Wife', 'Due To Illegal Parking',
       'Obscene Talks Women', 'House Arrest', 'Child',
       'Mad /Retarded Person', 'Crash Between Light Vehicles',
       'Dispute Between Relatives', 'Paving Dispute', 'Prostitution',
       'Due To Vehicle Damage', 'Unclaimed Vehicle',
       'Between Worker And Boss', 'Shop', 'Gathering Playing In Open',
       'Insult Of Senior Citizen', 'Email Hacking', 'Indecent Talks',
       'Unclaimed Women',
       'Information About Suspicious Object In The Vehicle',
       'Farm Forest Agriculture', 'In Private Vehicle', 'Other Campus',
       'Teasing In Building Or Premise',
       'No Proper Medical Support From Hospital Doctor', 'Hit And Run',
       'Sharp Weapons', 'Prv Has Taken Money From The Vehicle',
       'Gathering Open Walk In Group',
       'Misbehaviour With Child By Outsider',
       'Offensive/Obscene Material Post On Social Site', 'Aadhar Card',
       'Sos', 'Other Means', 'Woman Dead Body', 'Consuming Poison',
       'Making Fake Papers', 'Between Other Groups',
       'Electrical Equipment', 'Help For Transport',
       'Dispute Between Hijras And Men', 'Hit By Dividers',
       'Gathering Kotedaar Ration Shop', 'Harrasment By Inlaws',
       'Grp-Animal Accident By Train', 'Selling Goods Over Rate',
       'Website Hacking', 'From Any Device',
       'Green Tree Chopping Incident', 'Expelling Kids From Home',
       'Expelling Senior Citizen From House',
       'Information About Suspicious Person In The Vehicle',
       'Gathering Gambling Playing Cards', 'Child Marriage',
       'Identity Card', 'Unclaimed Child', 'Cycle', 'Iilegal Supply',
       'Driving License', 'Beating/Harassing/Torturing For Dowry',
       'Illegal Supply', 'Tablet/Pc/Laptop',
       'Harrassment Of Wife By Family Members',
       'Notification Of Police Inaction',
       'Making Or Selling Fake Artwork', 'Three Wheeler Vehicle',
       'Due To Strike', 'Inter Religion Marriage', 'Chain Snatching',
       'Illegal Mining River', 'Threatening',
       'Notice Of Negligence In Investigation',
       'Academic Certificates/Marsheet',
       'Conducting Election Meeting/Rally Without Permission',
       'Fake Registry', 'Money Distribution', 'Notice Of Delay In Work',
       'House Garbage Dump Huts Slum', 'Throttling',
       'Small Medium Large Industry', 'Cow Smuggling',
       'Crash Between Heavy Vehicles', 'Toxic Gas Leakage',
       'Gathering Construction Place',
       'Jumping Into Water (River, Canal,Lake,Swimming Pool, Pond Etc.)',
       'Between Neighbors', 'Obscene Message / Picture Post Of Men',
       'Iilegal Possession Of Narcotics', 'Inter Caste Marriage',
       'Other Vehicle', 'Senior Citizen Abuse', 'Prv Not Reached',
       'In Public Vehicle', 'Illegally Sending Abroad For Job',
       'Between Workers And Laborers', 'Police Help Required By 1090',
       'Buggery With A Child', 'Injury Due To Electical Current',
       'Notice Of Work To Abolish', 'Trafficking',
       'Violation Of The Instructions Of The Election Commission',
       'Encroachment On Road', 'Familymembers Harrassment Children',
       'Money', 'Iilegal Possession', 'Forced To Marry']

main = ['Area_Name','Group_Name','Sub_Group_Name',"STATE/UT","DISTRICT","Year","CRIME HEAD","States/UTs","Place Of Occurrence"]

main2 = []

common_date_col = ['Year',"Month","Day","Hour","Minute","Second","Date","Time","Recored_Time","DateTime","DateTime_UTC","DateTime_Local","DateTime_Local_UTC","DateTime_Local_UTC_Offset","DateTime_Local_UTC_Offset_Min","DateTime_Local_UTC_Offset_Min_Sec","DateTime_Local_UTC_Offset_Min_Sec_Milli","DateTime_Local_UTC_Offset_Min_Sec_Milli_Micro","DateTime_Local_UTC_Offset_Min_Sec_Milli_Micro_Nano"]
